#!/bin/sh

SCALE_FACTOR=`get-scale-factor.py`

env PULSE_PROP_application.icon_name="com.spotify.Client" /app/extra/bin/spotify --force-device-scale-factor=$SCALE_FACTOR "$@" &
`set-dark-theme-variant.py`
