#!/bin/sh

SCALE_FACTOR=`get-scale-factor.py`

/app/extra/bin/spotify --force-device-scale-factor=$SCALE_FACTOR&
sleep 2 # TODO: Actually detect when window appears
# Set dark variant
xprop -f _GTK_THEME_VARIANT 8u -set _GTK_THEME_VARIANT dark -name Spotify
